[package]
name = "bevy_prototype_networked_physics"
version = "0.1.0"
authors = ["Ernest Wong <sudo@ernestwong.nz>"]
edition = "2018"

[features]
default = [
    "use-webrtc",
]
use-udp = [
    "bevy_networking_turbulence/use-udp",
]
use-webrtc = [
    "bevy_networking_turbulence/use-webrtc",
]

[dependencies]
bevy = {version = "0.4", default-features = false}
bevy_networking_turbulence = {version = "0.2.0", default-features = false}
turbulence = "0.3.0"
serde="1.0.118"
