[package]
name = "crystalorb"
version = "0.1.0"
authors = ["Ernest Wong <sudo@ernestwong.nz>"]
edition = "2018"

[features]
default = [
    "serde/derive"
]

[dependencies]
tracing = "0.1.22"
serde="1.0.118"
